version: '3'

services:

  sense_module:
    build:
      context: ./Sense_module
      dockerfile: Dockerfile
    container_name: sense_module
    hostname: sense_module
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - TZ=Europe/Rome

  action_module:
    build:
      context: ./Action_module
      dockerfile: Dockerfile
    container_name: action_module
    hostname: action_module
    ports:
      - "8090:8090"
    expose:
      - 8090
    environment:
      - TZ=Europe/Rome
    depends_on:
      - sense_module